document.write("<p>Codigo del navegador: ");
document.write(info.codigo);
document.write("</p>");
document.write("<p>Version del navegador: ");
document.write(info.version);
document.write("</p>");
document.write("<p>Java está activado: ");
document.write(info.java);
document.write("</p>");
document.write("<p>Las cookies estan: ");
document.write(info.cookies);
document.write("</p>");
document.write("<p>Se está usando en: ");
document.write(info.plataforma);
document.write("</p>");
document.write("<p>Hay ");
document.write(info.numPlugins);
document.write("plugins</p>");
document.write("<p>Codigo del navegador: ");
document.write(info.codigo);
document.write("</p>");
document.write("<p>Cadena de agente usuario del navegador: ");
document.write(info.user);
document.write("</p>");
document.write("<p>Online: ");
document.write(info.online);
document.write("</p>");
document.write("<p>Producto (siempre 'Gecko'): ");
document.write(info.product);
document.write("</p>");